version: '3'

services:
  sample-app:
    container_name: sample-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
    environment:
      - NODE_ENV=development
      