# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build-test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    env:
      BUILD_PREFIX: true
      IS_MAIN: ${{ github.ref == 'refs/heads/main' }}
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      SCREENER_API_KEY: ${{ secrets.SCREENER_API_KEY }}
    steps:
      - uses: actions/checkout@v2

      - name: Build
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Build site
        env:
          CI: false
        run: |
          ls
          npm ci
          npm run build

      - name: Build storybook
        env:
          CI: false
        run: |
          ls
          npm run build.storybook
